---
url: 'http://127.37.0.1:18089/zabbix/api_jsonrpc.php'
debug: 'true'
jira_api_root:
  jira3: 'https://jira3dev.cerner.com'
jira_number: 'ETSDEV-3965'
health_check:
  nodes: [ 10.190.158.133 ]
  command:
